env: ENV_PROD
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
chain:
  chain_id: 5611
  chain_name: "opBNB"
  rpc_url: "https://opbnb-testnet.nodereal.io/v1/9e210feafbec4ed9bd48f855c2bd979a"
  start_block: 27320500
  offset_block: 1
contract:
  addr: "0x39afd848cd4a83cddd06f340ae584c547e53873d"
  tee_addr : "0x19baa72643aa11b28cb6251fd7596201778ead9a"
  topic: "0x99a038e9d345d0b12130b3b1fb003bf8f2d3a5c27ce2a800bbb1608efff6c591"
wallet:
  mode: 0
  private_key: "99a038e9d345d0b12130b3b1fb003bf8f2d3a5c27ce2a800bbb1608efff6c591"
  keystore_path: "/Users/alice/.keystore"
  keystore_password: "123456"
dacp:
  identity_path: "/data/conf/identity.json"
  tcb_path: "/data/conf/tcb.json"
  trusted_path: "/data/conf/trusted.json"